In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [10]:
X, y = load_iris(return_X_y=True)


In [11]:
X


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X_train_scaled

array([[ 0.7203254 , -0.607065  ,  0.46130051,  0.38100644],
       [ 0.48607324, -0.82781591,  0.63024068,  0.77742932],
       [-0.09955717, -0.82781591,  0.06710679, -0.01541645],
       [-1.50507014,  1.15894228, -1.56598149, -1.33682606],
       [ 0.48607324,  0.49668955,  0.5176139 ,  0.5131474 ],
       [-1.03656582, -2.37307229, -0.15814677, -0.27969837],
       [ 0.25182107, -0.38631409,  0.5176139 ,  0.24886548],
       [ 1.3059558 ,  0.27593864,  0.5176139 ,  0.24886548],
       [ 0.13469499, -0.38631409,  0.40498712,  0.38100644],
       [-1.50507014,  0.05518773, -1.28441455, -1.33682606],
       [ 0.25182107, -0.16556318,  0.63024068,  0.77742932],
       [ 0.48607324, -1.26931774,  0.68655407,  0.90957028],
       [-0.33380933, -0.16556318,  0.17973357,  0.11672452],
       [-1.27081798,  0.71744046, -1.22810116, -1.33682606],
       [-1.85644838, -0.16556318, -1.5096681 , -1.46896702],
       [-0.68518757,  1.37969319, -1.28441455, -1.33682606],
       [-1.1536919 ,  0.

In [15]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[ 0.7203254 , -0.607065  ,  0.46130051,  0.38100644],
       [ 0.48607324, -0.82781591,  0.63024068,  0.77742932],
       [-0.09955717, -0.82781591,  0.06710679, -0.01541645],
       [-1.50507014,  1.15894228, -1.56598149, -1.33682606],
       [ 0.48607324,  0.49668955,  0.5176139 ,  0.5131474 ],
       [-1.03656582, -2.37307229, -0.15814677, -0.27969837],
       [ 0.25182107, -0.38631409,  0.5176139 ,  0.24886548],
       [ 1.3059558 ,  0.27593864,  0.5176139 ,  0.24886548],
       [ 0.13469499, -0.38631409,  0.40498712,  0.38100644],
       [-1.50507014,  0.05518773, -1.28441455, -1.33682606],
       [ 0.25182107, -0.16556318,  0.63024068,  0.77742932],
       [ 0.48607324, -1.26931774,  0.68655407,  0.90957028],
       [-0.33380933, -0.16556318,  0.17973357,  0.11672452],
       [-1.27081798,  0.71744046, -1.22810116, -1.33682606],
       [-1.85644838, -0.16556318, -1.5096681 , -1.46896702],
       [-0.68518757,  1.37969319, -1.28441455, -1.33682606],
       [-1.1536919 ,  0.

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
X_train_scaled

array([[0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.58333333, 0.5       ,

In [18]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)
(X_train - X_min) / (X_max - X_min)

array([[0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.58333333, 0.5       ,